### ISSUE TITLE
Server cannot reach localhost

### ISSUE THREAD

**Issue by MichaelaRob** [MichaelaRob/mrob.ca#5]
Hello @thomasjbradley
I'm having a couple different issues right now with my website. The first is that when I try to open the localhost:400 in a web browser it's telling me that it cannot connect. My second issue is that my sitemap-entry.xml file seems to have something wrong with it. I'm not sure what it is but I've attached a photo of what my terminal is saying.

Thank you in advance for your help!

Michaela Robinson
<img width="569" alt="Screen Shot 2019-11-02 at 6 05 10 PM" src="https://user-images.githubusercontent.com/31852311/68077507-766b1c00-fd9b-11e9-8d7e-94df54c5be0b.png">

**Comment by thomasjbradley** [comment]
They are the same problem: the server won’t start because of the site map problem.

The `sitemap-entry.xml` file should be inside a folder named `_includes`
